/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package com.alfisal.sikeusekolah.form;

import javax.swing.JFrame;

/**
 *
 * @author ALFISAL-PUNJUNG
 */
public class FormUtama extends javax.swing.JFrame {
    FormAkun FormAkun =new FormAkun();
    /**
     * Creates new form FormUtama
     */
    public FormUtama() {
        initComponents();
        //fullscreen
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        desktopPane.add(FormAkun);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        saveAsMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        menuMaster = new javax.swing.JMenu();
        menuMasterAkun = new javax.swing.JMenuItem();
        menuMasterJurusan = new javax.swing.JMenuItem();
        menuMaterJurusan = new javax.swing.JMenuItem();
        menuMaterKelas = new javax.swing.JMenuItem();
        menuMaterSiswa = new javax.swing.JMenuItem();
        menuMaterBiayaTetap = new javax.swing.JMenuItem();
        menuMaterBiayaPmb = new javax.swing.JMenuItem();
        menuMaterBiayaLain = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fileMenu.setMnemonic('f');
        fileMenu.setText("File");

        openMenuItem.setMnemonic('o');
        openMenuItem.setText("Open");
        fileMenu.add(openMenuItem);

        saveMenuItem.setMnemonic('s');
        saveMenuItem.setText("Save");
        fileMenu.add(saveMenuItem);

        saveAsMenuItem.setMnemonic('a');
        saveAsMenuItem.setText("Save As ...");
        saveAsMenuItem.setDisplayedMnemonicIndex(5);
        fileMenu.add(saveAsMenuItem);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        menuMaster.setMnemonic('e');
        menuMaster.setText("Master");

        menuMasterAkun.setMnemonic('t');
        menuMasterAkun.setText("Akun");
        menuMasterAkun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMasterAkunActionPerformed(evt);
            }
        });
        menuMaster.add(menuMasterAkun);

        menuMasterJurusan.setMnemonic('y');
        menuMasterJurusan.setText("Angkatan");
        menuMasterJurusan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMasterJurusanActionPerformed(evt);
            }
        });
        menuMaster.add(menuMasterJurusan);

        menuMaterJurusan.setMnemonic('p');
        menuMaterJurusan.setText("Jurusan");
        menuMaterJurusan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMaterJurusanActionPerformed(evt);
            }
        });
        menuMaster.add(menuMaterJurusan);

        menuMaterKelas.setMnemonic('d');
        menuMaterKelas.setText("Kelas");
        menuMaterKelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMaterKelasActionPerformed(evt);
            }
        });
        menuMaster.add(menuMaterKelas);

        menuMaterSiswa.setText("Siswa");
        menuMaterSiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMaterSiswaActionPerformed(evt);
            }
        });
        menuMaster.add(menuMaterSiswa);

        menuMaterBiayaTetap.setText("Biaya Tetap");
        menuMaterBiayaTetap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMaterBiayaTetapActionPerformed(evt);
            }
        });
        menuMaster.add(menuMaterBiayaTetap);

        menuMaterBiayaPmb.setText("Biaya PMB");
        menuMaterBiayaPmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMaterBiayaPmbActionPerformed(evt);
            }
        });
        menuMaster.add(menuMaterBiayaPmb);

        menuMaterBiayaLain.setText("Biaya Lain");
        menuMaterBiayaLain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMaterBiayaLainActionPerformed(evt);
            }
        });
        menuMaster.add(menuMaterBiayaLain);

        menuBar.add(menuMaster);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");

        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("Contents");
        helpMenu.add(contentMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1108, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void menuMasterAkunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMasterAkunActionPerformed
        desktopPane.removeAll();
        desktopPane.repaint();
        FormAkun formAkun=new FormAkun();
        desktopPane.add(formAkun);
        formAkun.setVisible(true);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_menuMasterAkunActionPerformed

    private void menuMasterJurusanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMasterJurusanActionPerformed
        // TODO add your handling code here:
        desktopPane.removeAll();
        desktopPane.repaint();
        FormAngkatan formAngkatan=new FormAngkatan();
        desktopPane.add(formAngkatan);
        formAngkatan.setVisible(true);
    }//GEN-LAST:event_menuMasterJurusanActionPerformed

    private void menuMaterJurusanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMaterJurusanActionPerformed
        // TODO add your handling code here:
        desktopPane.removeAll();
        desktopPane.repaint();
        FormJurusan formJurusan=new FormJurusan();
        desktopPane.add(formJurusan);
        formJurusan.setVisible(true);
    }//GEN-LAST:event_menuMaterJurusanActionPerformed

    private void menuMaterKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMaterKelasActionPerformed
        // TODO add your handling code here:
        desktopPane.removeAll();
        desktopPane.repaint();
        FormKelas formKelas=new FormKelas();
        desktopPane.add(formKelas);
        formKelas.setVisible(true);
    }//GEN-LAST:event_menuMaterKelasActionPerformed

    private void menuMaterSiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMaterSiswaActionPerformed
        // TODO add your handling code here:
         desktopPane.removeAll();
        desktopPane.repaint();
        FormSiswa formSiswa=new FormSiswa();
        desktopPane.add(formSiswa);
        formSiswa.setVisible(true);
    }//GEN-LAST:event_menuMaterSiswaActionPerformed

    private void menuMaterBiayaTetapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMaterBiayaTetapActionPerformed
        // TODO add your handling code here:
        desktopPane.removeAll();
        desktopPane.repaint();
        FormBiayaTetap formBiayaTetap=new FormBiayaTetap();
        desktopPane.add(formBiayaTetap);
        formBiayaTetap.setVisible(true);
    }//GEN-LAST:event_menuMaterBiayaTetapActionPerformed

    private void menuMaterBiayaPmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMaterBiayaPmbActionPerformed
        // TODO add your handling code here:
        desktopPane.removeAll();
        desktopPane.repaint();
        FormBiayaPmb formBiayaPmb=new FormBiayaPmb();
        desktopPane.add(formBiayaPmb);
        formBiayaPmb.setVisible(true);
    }//GEN-LAST:event_menuMaterBiayaPmbActionPerformed

    private void menuMaterBiayaLainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMaterBiayaLainActionPerformed
        // TODO add your handling code here:
        desktopPane.removeAll();
        desktopPane.repaint();
        FormBiayaLain formBiayaLain=new FormBiayaLain();
        desktopPane.add(formBiayaLain);
        formBiayaLain.setVisible(true);
    }//GEN-LAST:event_menuMaterBiayaLainActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem contentMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuMaster;
    private javax.swing.JMenuItem menuMasterAkun;
    private javax.swing.JMenuItem menuMasterJurusan;
    private javax.swing.JMenuItem menuMaterBiayaLain;
    private javax.swing.JMenuItem menuMaterBiayaPmb;
    private javax.swing.JMenuItem menuMaterBiayaTetap;
    private javax.swing.JMenuItem menuMaterJurusan;
    private javax.swing.JMenuItem menuMaterKelas;
    private javax.swing.JMenuItem menuMaterSiswa;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JMenuItem saveAsMenuItem;
    private javax.swing.JMenuItem saveMenuItem;
    // End of variables declaration//GEN-END:variables

}
